#!/bin/bash
# Download pci.ids and generate src/drivers/pci_ids.c with vendor and
# class lookup tables. Run this whenever you want to refresh the tables.
#
# The generated file is committed to git so the build does not need
# network access.
cd "$(dirname "$0")/.."
set -euo pipefail

URL="https://pci-ids.ucw.cz/v2.2/pci.ids"
CACHE=$(mktemp)
OUT=src/drivers/pci_ids.c

trap 'rm -f "$CACHE"' EXIT

echo "[gen_pci_ids] Downloading $URL..."
if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$URL" -o "$CACHE"
elif command -v wget >/dev/null 2>&1; then
    wget -q "$URL" -O "$CACHE"
else
    echo "Error: need curl or wget" >&2
    exit 1
fi

echo "[gen_pci_ids] Generating $OUT..."

awk '
BEGIN {
    # Whitelist of vendor IDs to embed. Anything not on this list is
    # skipped to keep the kernel binary small (the full pci.ids is ~1.5 MB
    # and overflows 16-bit relocations in early kmain.s).
    keep["1002"] = 1   # AMD/ATI GPU
    keep["1022"] = 1   # AMD CPU
    keep["1106"] = 1   # VIA
    keep["1131"] = 1   # Conexant/NXP
    keep["1180"] = 1   # Ricoh
    keep["11ab"] = 1   # Marvell
    keep["1234"] = 1   # Bochs (QEMU stdvga)
    keep["126f"] = 1   # Silicon Motion
    keep["144d"] = 1   # Samsung
    keep["14e4"] = 1   # Broadcom
    keep["15b3"] = 1   # Mellanox
    keep["168c"] = 1   # Qualcomm Atheros
    keep["1969"] = 1   # Atheros / Qualcomm Atheros
    keep["1af4"] = 1   # Red Hat virtio
    keep["1b21"] = 1   # ASMedia
    keep["1b36"] = 1   # Red Hat Q35 chipset
    keep["1b73"] = 1   # Fresco Logic
    keep["1c5c"] = 1   # SK hynix
    keep["1cc1"] = 1   # ADATA
    keep["1cc4"] = 1   # Solidigm
    keep["1d6b"] = 1   # Linux Foundation
    keep["1e0f"] = 1   # KIOXIA
    keep["8086"] = 1   # Intel
    keep["8087"] = 1   # Intel
    keep["10de"] = 1   # NVIDIA
    keep["10ec"] = 1   # Realtek

    print "// Generated by scripts/gen_pci_ids.sh from pci.ids."
    print "// DO NOT EDIT MANUALLY. Re-run the script to refresh."
    print "// Filtered to a vendor whitelist; see scripts/gen_pci_ids.sh."
    print ""
    print "#include <drivers/pci.h>"
    print ""
    print "typedef struct { uint16 id; const char *name; } PciVendorEntry;"
    print "typedef struct { uint8 cls; uint8 sub; const char *name; } PciClassEntry;"
    print ""
}

# Vendor line: "XXXX  Vendor Name"
/^[0-9a-fA-F]{4}  / {
    if (in_vendors == 0) {
        print "static const PciVendorEntry pci_vendors[] = {"
        in_vendors = 1
    }
    id = substr($0, 1, 4)
    if (!(id in keep)) next
    name = substr($0, 7)
    gsub(/"/, "\\\"", name)
    gsub(/\?\?/, "?\\?", name)   # avoid trigraph warnings
    printf "    { 0x%s, \"%s\" },\n", id, name
    next
}

# Class line: "C XX  Class Name"
/^C [0-9a-fA-F]{2}  / {
    if (in_vendors == 1) {
        print "    { 0, 0 }"
        print "};"
        print ""
        print "static const PciClassEntry pci_classes[] = {"
        in_vendors = 2
    }
    cls = substr($0, 3, 2)
    name = substr($0, 7)
    gsub(/"/, "\\\"", name)
    gsub(/\?\?/, "?\\?", name)
    printf "    { 0x%s, 0xFF, \"%s\" },\n", cls, name
    last_cls = cls
    next
}

# Subclass line: "\tXX  Subclass Name" (only after a class line)
/^\t[0-9a-fA-F]{2}  / {
    if (in_vendors == 2) {
        sub_id = substr($0, 2, 2)
        name = substr($0, 6)
        gsub(/"/, "\\\"", name)
        gsub(/\?\?/, "?\\?", name)
        printf "    { 0x%s, 0x%s, \"%s\" },\n", last_cls, sub_id, name
    }
    next
}

# Skip everything else (comments, device lines, deeper indentation)
{ next }

END {
    if (in_vendors == 1) {
        print "    { 0, 0 }"
        print "};"
        print ""
        print "static const PciClassEntry pci_classes[] = {"
    }
    print "    { 0, 0, 0 }"
    print "};"
    print ""
    print "const char *pci_vendor_name(uint16 vendor_id) {"
    print "    for (uint32 i = 0; pci_vendors[i].name; i++)"
    print "        if (pci_vendors[i].id == vendor_id) return pci_vendors[i].name;"
    print "    return 0;"
    print "}"
    print ""
    print "const char *pci_class_name(uint8 cls, uint8 sub) {"
    print "    // First try exact (cls, sub) match"
    print "    for (uint32 i = 0; pci_classes[i].name; i++)"
    print "        if (pci_classes[i].cls == cls && pci_classes[i].sub == sub)"
    print "            return pci_classes[i].name;"
    print "    // Fall back to class-only match (sub == 0xFF)"
    print "    for (uint32 i = 0; pci_classes[i].name; i++)"
    print "        if (pci_classes[i].cls == cls && pci_classes[i].sub == 0xFF)"
    print "            return pci_classes[i].name;"
    print "    return 0;"
    print "}"
}
' "$CACHE" > "$OUT"

LINES=$(wc -l < "$OUT")
SIZE=$(wc -c < "$OUT")
echo "[gen_pci_ids] Wrote $OUT ($LINES lines, $SIZE bytes)"
